version: "3"

services:
  cosmos:
    container_name: "cosmos"
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    expose:
      - 8081:8081
    ports:
      - 8081:8081
      - 10250-10255:10250-10255
    deploy:
      resources:
        limits:
          memory: "4GB"

  server:
    container_name: "backend-server"
    build:
      context: .
      dockerfile: ./server/Dockerfile
    expose:
      - 8000:8000
    ports:
      - 8000:8000
    volumes:
      - ./server/:/server
    command:
      npm run backend:dev
    depends_on:
      - cosmos

  client:
    container_name: "app-ui"
    build: 
      context: .
      dockerfile: ./src/Dockerfile
    expose:
      - 3000:3000
    ports:
      - 3000:3000
    volumes:
      - ./:/client
    command:
      npm run dev
    depends_on:
      - server
